exclude = [
    "https://api\\.neurocipher\\.io/.*",
    "https://stg-api\\.neurocipher\\.io/.*",
    "http://localhost:8000/.*",
    "https://schemas\\.neurocipher\\.io/.*",
    "https://neurocipher\\.io/problems/.*",
    "https://kv-seg-prod\\.vault\\.azure\\.net/.*",
    "https://kv-seg-prod\\.vault\\.azure\\.net/keys/attestation-key/.*"
]

accept = [200, 201, 202, 204, 301, 302]
